module.exports = (sequelize, Sequelize) => {
  const ReadingTopic = sequelize.define("reading_topic", {
    id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true,
      field: "reading_topic_id",
    },
    level: {
      type: Sequelize.ENUM("beginner", "intermediate", "expert"),
      allowNull: false,
      field: "reading_topic_level",
    },
    title: {
      type: Sequelize.STRING(255),
      allowNull: false,
      field: "reading_topic_title",
    },
    contentText: {
      type: Sequelize.TEXT,
      allowNull: false,
      field: "reading_topic_content_text",
    },
    isAutoGenerated: {
      type: Sequelize.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      field: "reading_topic_is_auto_generated",
    },
    createdByUserId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "user",
        key: "user_id",
      },
      field: "reading_topic_created_by_user_id",
    },
  }, {
    timestamps: true,
    createdAt: "reading_topic_created_at",
    updatedAt: "reading_topic_updated_at",
  });

  return ReadingTopic;
};