module.exports = (sequelize, Sequelize) => {
  const SpeakingTopic = sequelize.define("speaking_topic", {
    id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true,
      field: "speaking_topic_id",
    },
    level: {
      type: Sequelize.ENUM("beginner", "intermediate", "expert"),
      allowNull: false,
      field: "speaking_topic_level",
    },
    topicType: {
      type: Sequelize.ENUM("Informal Email", "Formal Email", "General"),
      allowNull: false,
      field: "speaking_topic_type",
    },
    promptText: {
      type: Sequelize.TEXT,
      allowNull: false,
      field: "speaking_topic_prompt_text",
    },
    isAutoGenerated: {
      type: Sequelize.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      field: "speaking_topic_is_auto_generated",
    },
    createdByUserId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "user",
        key: "user_id",
      },
      field: "speaking_topic_created_by_user_id",
    },
  }, {
    timestamps: true,
    createdAt: "speaking_topic_created_at",
    updatedAt: "speaking_topic_updated_at",
  });

  return SpeakingTopic;
};