module.exports = (sequelize, Sequelize) => {
  const TopicSelect = sequelize.define("topicselect", {
    id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true,
      field: "topicselect_id",
    },
    level: {
      type: Sequelize.ENUM("beginner", "intermediate", "expert"),
      allowNull: false,
      field: "topicselect_level",
    },
    type: {
      type: Sequelize.ENUM("reading_skills", "writing_skills", "speaking_skills"),
      allowNull: false,
      field: "topicselect_type",
    },
    promptText: {
      type: Sequelize.TEXT,
      allowNull: false,
      field: "topicselect_prompt_text",
    },
    query: {
      type: Sequelize.TEXT,
      allowNull: true,
      field: "topicselect_query",
    },
    isAutoGenerated: {
      type: Sequelize.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      field: "topicselect_is_auto_generated",
    },
    createdByUserId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "user",
        key: "user_id",
      },
      field: "topicselect_created_by_user_id",
    },
  }, {
    
    timestamps: true,
    createdAt: "topicselect_created_at",
    updatedAt: "topicselect_updated_at",
  });

  return TopicSelect;
};
