module.exports = (sequelize, Sequelize) => {
  const WritingPrompt = sequelize.define("writing_prompt", {
    id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true,
      field: "writing_prompt_id",
    },
    level: {
      type: Sequelize.ENUM("beginner", "intermediate", "expert"),
      allowNull: false,
      field: "writing_prompt_level",
    },
    name: {
      type: Sequelize.ENUM(
        "Expository",
        "Descriptive",
        "Persuasive",
        "Narrative",
        "Informal Email",
        "Formal Email"
      ),
      allowNull: false,
      field: "writing_prompt_name",
    },
    promptText: {
      type: Sequelize.TEXT,
      allowNull: false,
      field: "writing_prompt_text",
    },
    isAutoGenerated: {
      type: Sequelize.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      field: "writing_prompt_is_auto_generated",
    },
    createdByUserId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "user",
        key: "user_id",
      },
      field: "writing_prompt_created_by_user_id",
    },
  }, {
    timestamps: true,
    createdAt: "writing_prompt_created_at",
    updatedAt: "writing_prompt_updated_at",
  });

  return WritingPrompt;
};