// Constants for Input Types
const INPUT_TYPES = {
  TEXT_INPUT: "TEXT_INPUT",
  TEXT_AREA: "TEXT_AREA",
  CHECKBOX: "CHECKBOX",
  RADIO_BUTTON: "RADIO_BUTTON",
  DROPDOWN: "DROPDOWN",
  MULTI_SELECT_DROPDOWN: "MULTI_SELECT_DROPDOWN",
  DATE_PICKER: "DATE_PICKER",
  TIME_SELECTOR: "TIME_SELECTOR",
  FILE_UPLOAD: "FILE_UPLOAD",
  TOGGLE_SWITCH: "TOGGLE_SWITCH",
  RANGE_SELECTOR: "RANGE_SELECTOR",
  STAR_RATING: "STAR_RATING",
  HIDDEN_FIELD: "HIDDEN_FIELD",
};

// Constants for Question Types
const QUESTION_TYPES = {
  DEMOGRAPHIC: "DEMOGRAPHIC",
  SATISFACTION: "SATISFACTION",
  LIKELIHOOD: "LIKELIHOOD",
  OPEN_ENDED: "OPEN_ENDED",
  YES_NO: "YES_NO",
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
  MATRIX: "MATRIX",
  RANKING: "RANKING",
  FOLLOW_UP: "FOLLOW_UP",
  PROBLEM_IDENTIFICATION: "PROBLEM_IDENTIFICATION",
  IMPROVEMENT_SUGGESTION: "IMPROVEMENT_SUGGESTION",
  EXPERIENCE_RATING: "EXPERIENCE_RATING",
  COMPLIANCE: "COMPLIANCE",
  PERFORMANCE_METRIC: "PERFORMANCE_METRIC",
  NPS: "NPS",
  CSAT: "CSAT",
  RATING: "RATING",
  CES: "CES",
};


export { INPUT_TYPES, QUESTION_TYPES };
